export const LOGIN = 'business-admins-by-usersub';
export const STORE_EMAIL = 'AUTH.STORE_EMAIL';
export const STORE_USER_SUCCESS = 'AUTH.STORE_USER_SUCCESS';
export const STORE_USER_ERROR = 'AUTH.STORE_USER_ERROR';
export const REGISTER_AWS_SUCCESS = 'REGISTER_AWS_SUCCESS';
export const REGISTER_AWS_ERROR = 'REGISTER_AWS_ERROR';
export const CONFIRM_SIGNUP_SUCCESS = 'CONFIRM_SIGNUP_SUCCESS';
export const CONFIRM_SIGNUP_ERROR = 'CONFIRM_SIGNUP_ERROR';
export const HANDLE_VERIFICATION_MODAL = 'HANDLE_VERIFICATION_MODAL';
export const CLOSE_REGISTER_SUCCESS_MODAL = 'CLOSE_REGISTER_SUCCESS_MODAL';

export const RESET_ERROR_MESSAGE = 'AUTH.RESET_ERROR_MESSAGE';
